version: "3.5"
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - app
    restart: always
    volumes:
      - ./.docker/apache/data/ssl_certs:/var/lib/https-portal
    environment:
      DOMAINS: 'osurv.net -> http://app'
      STAGE: 'production'
      CLIENT_MAX_BODY_SIZE: 0
      # FORCE_RENEW: 'true'
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: osurv-docker
    restart: always
    volumes:
      - "./.docker/app_data/accounts:/app/accounts"
      - "./.docker/app_data/requestList:/app/requestList"
      - "./.docker/app_data/pledgers:/app/php/patreon/pledgers"
      - "./.docker/app_data/client:/app/client"
      - "./.htaccess:/app/.htaccess"
      - "app_files:/app"
    links:
      - mysql
  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
    restart: always
    volumes:
      - "./.docker/mysql/osurv.sql:/docker-entrypoint-initdb.d/osurv.sql"
      - "./.docker/mysql/data:/var/lib/mysql"
  sftp:
    image: atmoz/sftp
    restart: always
    depends_on:
      - app
    volumes:
      - "./.docker/ssh/host_keys/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key"
      - "./.docker/ssh/host_keys/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key"
      - "./.docker/ssh/keys/:/home/sftp/.ssh/keys/:ro"
      - "./.docker/app_data/accounts:/home/sftp/www/accounts"
      - "./.docker/app_data/requestList:/home/sftp/www/requestList"
      - "./.docker/app_data/pledgers:/home/sftp/www/php/patreon/pledgers"
      - "./.docker/app_data/client:/home/sftp/www/client"
      - "./.htaccess:/home/sftp/www/.htaccess"
      - "app_files:/home/sftp/www"
      - "./.docker/ssh/startup.sh:/etc/sftp.d/startup.sh"
    ports:
      - "222:22"
    command: sftp::1001:33:www
volumes:
  app_files:
