version: "3.5"
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - app
    restart: always
    volumes:
      - ./.docker/apache/data/ssl_certs:/var/lib/https-portal
    environment:
      DOMAINS: 'osurv.com -> http://app'
      STAGE: 'local'
      CLIENT_MAX_BODY_SIZE: 0
      # STAGE: 'production'
      # FORCE_RENEW: 'true'
  app:
    build:
      context: .
      dockerfile: .docker/DockerfileDev
    image: osurv-docker
    volumes:
      - "app_files:/app"
      - "./.docker/app_data/accounts:/app/accounts"
      - "./.docker/app_data/requestList:/app/requestList"
      - "./.docker/app_data/pledgers:/app/php/patreon/pledgers"
      - "./.htaccess:/app/.htaccess"
    links:
      - mysql
    environment:
      XDEBUG_CONFIG: remote_host=172.17.0.1 #Change with your local ip address
  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
    volumes:
      - "./.docker/mysql/osurv.sql:/docker-entrypoint-initdb.d/osurv.sql"
      - "./.docker/mysql/data:/var/lib/mysql"
  sftp:
    image: atmoz/sftp
    depends_on:
      - app
    volumes:
    - "./.docker/ssh/host_keys/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key"
    - "./.docker/ssh/host_keys/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key"
    - "./.docker/ssh/keys/:/home/sftp/.ssh/keys/:ro"
    - "app_files:/home/sftp"
    ports:
    - "22:22"
    command: sftp::33
volumes:
  app_files:
