version: "3.5"
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: osurv-docker
    ports:
      - "80:80"
    volumes:
      - app_files:/app_data
      - ./accounts:/app_data/accounts
      - ./requestList:/app_data/requestList
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
    volumes:
    - ./.docker/mysql/osurv.sql:/docker-entrypoint-initdb.d/osurv.sql #Import database structure
    - ./.docker/mysql/data:/var/lib/mysql
  sftp:
    image: atmoz/sftp
    depends_on:
      - app
    volumes:
    - ./.docker/ssh/host_keys/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key
    - ./.docker/ssh/host_keys/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key
    - ./.docker/ssh/keys/id_recorder.pub:/home/foo/.ssh/keys/id_recorder.pub:ro
    - ./.docker/ssh/keys/id_storage.pub:/home/foo/.ssh/keys/id_storage.pub:ro
    - app_files:/home/foo
    ports:
    - "22:22"
    command: foo::33
volumes:
  app_files: